This notebook is meant to make a python note to follow the blog post series of this:
https://mpatacchiola.github.io/blog/2016/12/09/dissecting-reinforcement-learning.html

## Checking If Bellman Optimality Equation Works

With the optimal policy, the state-value function satisfies the following Bellman Optimality Equation:

\begin{equation}
v_*(s) = max_{a \in A} (R_s^a + \gamma \Sigma_{s'\in S}P_{ss'}^av_*(s'))
\end{equation}

In [1]:
import numpy as np

In [2]:
"""
Transition matrix - 3 dimensions
First dimention d=12: From state (including inadmissible cell #6)
Seond dimension d=12: To state (including terminal state #4 & 8 and inadmissible cell #6)
Third dimension d=4: Action (0-4): 0=Up, 1=Left, 2=Down, 3=Right

This matrix represents the situation that the selection of action does not necessarily give deterministic moves, 
but a stochastic ones with some mis-directed moves.
""" 

P = np.load("T.npy")
P

array([[[0.9, 0.9, 0.1, 0.1],
        [0.1, 0. , 0.1, 0.8],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0.1, 0.8, 0.1],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ]],

       [[0.1, 0.8, 0.1, 0. ],
        [0.8, 0.2, 0.8, 0.2],
        [0.1, 0. , 0.1, 0.8],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ]],

       [[0. , 0. , 0. , 0. ],
        [0.1, 0.8, 0.1, 0. ],
        [0.8, 0.1, 0. , 0.1],
        [0.1, 0. , 0.1, 0.8],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0.1, 0.8, 0.1],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
      

In [3]:
P[:,:,0]

array([[0.9, 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.1, 0.8, 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.1, 0.8, 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.8, 0. , 0. , 0. , 0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.8, 0. , 0. , 0. , 0.1, 0.1, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.8, 0. , 0. , 0. , 0.1, 0.1, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0.8, 0.1, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.8, 0. , 0. , 0.1, 0. , 0.1],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.8, 0. , 0. , 0.1, 0.1]])

In [4]:
def return_state_vf_optimal(s,P,v,r,gamma):
    """
    @return
    state-value function at s==1 cell with the optimal policy reflected on transition probability matrix P
    
    @param
    s - array with n=12: state -> 1 at the place agent exists on, 0 otherwise
    P - 3 dim matrix with n=12x12x4: transition probability matrix on the policy
    v - array with n=12: state-value functions
    r - scalar: immediate reward
    gamma - scalar: discount rate    
    """
    action_array = np.zeros(4)
    for a in range(4):
        action_array[a] = np.sum(np.multiply(v, np.dot(s, P[:,:,a])))
    return r + gamma * np.max(action_array)

In [5]:
def main():
    s = np.array([[0.0, 0.0, 0.0, 0.0, 
                   0.0, 0.0, 0.0, 0.0, 
                   1.0, 0.0, 0.0, 0.0]])
    P = np.load("T.npy")
    #State-value function with optimal policy
    v = np.array([[0.812, 0.868, 0.918,   1.0,
                   0.762,   0.0, 0.660,  -1.0,
                   0.705, 0.655, 0.611, 0.388]])
    r = -0.04
    gamma = 1.0

    utility_11 = return_state_vf_optimal(s, P, v, r, gamma)
    print("Utility of state (1,1): " + str(utility_11))
    
if __name__ == "__main__":
    main()

Utility of state (1,1): 0.7056


## Value Iteration Algorithm

Value Iteration algorithm is to get the optimal state-value functions directly by iterations such that:

\begin{equation}
v_{k+1}(s) = max_{a \in A} (R_s^a + \gamma \Sigma_{s'\in S}P_{ss'}^av_{k}(s'))
\end{equation}

If $\gamma =1$, it never converges. As it gets closer to 1.0, the final numbers are close enough to the true optimal numbers.

The drawback of value iteration algorithm is it does not provide the optimal policy as it is, though it is indirectly given by choosing the best action $a$ among the action-value functions derived from:

\begin{equation}
q_{*}(s,a) = R_s^a + \gamma \Sigma_{s'\in S}P_{ss'}^av_{*}(s')
\end{equation}

In [20]:
%time
def main():
    #Change as you want
    tot_states = 12
    gamma = 0.9999999 #Discount factor
    iteration = 0 #Iteration counter
    epsilon = 0.001 #Stopping criteria small value

    #List containing the data for each iteation
    graph_list = list()

    #Transition matrix loaded from file (It is too big to write here)
    P = np.load("T.npy")

    #Reward vector
    r = np.array([-0.04, -0.04, -0.04,  +1.0,
                  -0.04,   0.0, -0.04,  -1.0,
                  -0.04, -0.04, -0.04, -0.04])    

    #Initial state-value function vectors
    v_k0 = np.array([0.0, 0.0, 0.0,  0.0,
                   0.0, 0.0, 0.0,  0.0,
                   0.0, 0.0, 0.0,  0.0])
    v_k1 = np.array([0.0, 0.0, 0.0,  0.0,
                    0.0, 0.0, 0.0,  0.0,
                    0.0, 0.0, 0.0,  0.0])

    while True:
        delta = 0
        v_k0 = v_k1.copy()
        iteration += 1
        graph_list.append(v_k0)
        for c in range(tot_states):
            reward = r[c]
            s = np.zeros((1,tot_states))
            s[0,c] = 1.0
            v_k1[c] = return_state_vf_optimal(s, P, v_k0, reward, gamma)
            delta = max(delta, np.abs(v_k1[c] - v_k0[c])) #Stopping criteria       
        if delta < epsilon * (1 - gamma) / gamma:
                print("=================== FINAL RESULT ==================")
                print("Iterations: " + str(iteration))
                print("Delta: " + str(delta))
                print("Gamma: " + str(gamma))
                print("Epsilon: " + str(epsilon))
                print("===================================================")
                print(v_k0[0:4])
                print(v_k0[4:8])
                print(v_k0[8:12])
                print("===================================================")
                break
#     print(graph_list)

if __name__ == "__main__":
    main()

Wall time: 0 ns
=================== FINAL RESULT ==================
Iterations: 41
Delta: 9.328160466282043e-11
Gamma: 0.9999999
Epsilon: 0.001
[0.81155786 0.86780798 0.91780809 1.        ]
[ 0.76155776  0.          0.66027378 -1.        ]
[0.70530765 0.65530757 0.61141485 0.38792427]


## Iterative Policy Evaluation + Policy Iteration
Iterative Policy Evaluation + Policy Iteration is another iterative approach to obtain the optimal state-value functions and optimal policy with alternation of evaluation of policy and exploration of best policy (by greedy algorithm) with the recent evaluation.

<br>

Here's one iteration of Iterative Policy Evaluation:

\begin{equation}
v_{k+1}(s) = \Sigma_{a \in A} \pi_k(a|s) (R_s^a + \gamma \Sigma_{s'\in S}P_{ss'}^av_{k}(s'))
\end{equation}

Repeating this until the state-value function conversges to the state-VF at cycle $t$ as $v_{t}(s)$ based on the current policy.

<br>

Here's Policy Iteration using evaluated cycle $t$ state-value function $v_{t}(s)$ (greedy algorithm):

\begin{equation}
\newcommand{\argmax}{\mathop{\rm arg~max}\limits}
\newcommand{\argmin}{\mathop{\rm arg~min}\limits}
\pi_{t+1}(a|s) = \argmax_a (R_s^a + \gamma \Sigma_{s'\in S} P_{ss'}^av_{t}(s'))
\end{equation}

<br>

Repeating Iterative Policy Evaluation and Policy Iteration, reach at the optimal policy and state-value function:

\begin{equation}
\pi_{1}(a|s) \rightarrow v_{1}(s) \rightarrow \pi_{2}(a|s) \rightarrow v_{2}(s) \rightarrow ... \rightarrow \pi_{t}(a|s) \rightarrow v_{t}(s) \rightarrow \pi_{t+1}(a|s) \rightarrow ... \rightarrow  \pi_{*}(a|s) \rightarrow v_{*}(s)
\end{equation}



In [15]:
def policy_evaluation(s,P,v,r,gamma,po):
    """
    @return: a scalar value
    converged state-value function at s==1 cell with the optimal policy reflected on transition probability matrix P
    
    @param
    s - array with n=12: state -> 1 at the place agent exists on, 0 otherwise
    P - 3 dim matrix with n=12x12x4: transition probability matrix on the policy
    v - array with n=12: state-value functions
    r - scalar: immediate reward
    gamma - scalar: discount rate  
    po - array with n=12x4: current policy representing the probability of taking action 0=Up, 1=Left, 2=Down, 3=Right
    """    
    action_array = np.zeros(4)
    for a in range(4):
        action_array[a] = np.sum(np.multiply(v, np.dot(s, P[:,:,a])))
    return r + gamma * np.sum(np.multiply(action_array, np.dot(s, po)))
    

def policy_iteration(s,P,v,r,gamma):
    """
    @return: an array with n=4
    probabilities of taking actions with indices 0=Up, 1=Left, 2=Down, 3=Right
    
    @param
    s - array with n=12: state -> 1 at the place agent exists on, 0 otherwise
    P - 3 dim matrix with n=12x12x4: transition probability matrix on the policy
    v - array with n=12: state-value functions
    r - scalar: immediate reward
    gamma - scalar: discount rate  
    """        
    action_array = np.zeros(4)
    for a in range(4):
        action_array[a] = np.sum(np.multiply(v, np.dot(s, P[:,:,a])))
    po_array = np.zeros(4)
    for a in range(4):
        if action_array[a]==np.max(action_array):
            po_array[a]=1
    return po_array / np.sum(po_array)


In [17]:
%time
def main():
    #Change as you want
    tot_states = 12
    gamma = 0.9999999 #Discount factor
    iteration = 0 #Iteration counter
    epsilon_v = 0.001 #Stopping criteria of iterative policy evaluation
    epsilon_p = 0.001 #Stopping criteria of policy iteration 

    #Transition matrix loaded from file (It is too big to write here)
    P = np.load("T.npy")

    #Reward vector
    r = np.array([-0.04, -0.04, -0.04,  +1.0,
                  -0.04,   0.0, -0.04,  -1.0,
                  -0.04, -0.04, -0.04, -0.04])    

    #Initial state-value function vectors
#     v_k0 = np.array([0.0, 0.0, 0.0,  0.0,
#                    0.0, 0.0, 0.0,  0.0,
#                    0.0, 0.0, 0.0,  0.0])
    v_k1 = np.array([0.0, 0.0, 0.0,  0.0,
                    0.0, 0.0, 0.0,  0.0,
                    0.0, 0.0, 0.0,  0.0])
    
    #Initial policy matrix
    po_k1 = [[0. , 0. , 0.5, 0.5],
            [0. , 0.33,0.33,0.34],
            [0. , 0.33,0.33,0.34],
            [0. , 0. , 0. , 0. ],
            [0.5, 0. , 0.5, 0. ],
            [0. , 0. , 0. , 0. ],
            [0.33,0. ,0.33, 0.34],
            [0. , 0. , 0. , 0. ],
            [0.5, 0. , 0. , 0.5],
            [0. , 0.5, 0. , 0.5],
            [0.33,0.33, 0. ,0.33],
            [0.5, 0.5, 0. , 0. ]]


    while True:       
        delta_p = 0
        po_k0 = po_k1.copy()
        iteration += 1
    
        while True:
            delta_v = 0
            v_k0 = v_k1.copy()
#             graph_list.append(v_k0)
            for c in range(tot_states):
                reward = r[c]
                s = np.zeros((1,tot_states))
                s[0,c] = 1.0
                v_k1[c] = policy_evaluation(s, P, v_k0, reward, gamma, po_k0)
                delta_v = max(delta_v, np.abs(v_k1[c] - v_k0[c])) #Stopping criteria   

            if delta_v < epsilon_v * (1 - gamma) / gamma:
                break
                
        for c in range(tot_states):
            reward = r[c]
            s = np.zeros((1,tot_states))
            s[0,c] = 1.0
            po_k1[c] = policy_iteration(s, P, v_k1, reward, gamma)
            for a in range(4):
                delta_p = max(delta_p, np.abs(po_k1[c][a] - po_k0[c][a])) #Stopping criteria  
            
        if delta_p < epsilon_p:
            print("=================== FINAL RESULT ==================")
            print("Iterations: " + str(iteration))
#             print("Delta: " + str(delta))
            print("Gamma: " + str(gamma))
            print("Epsilon for state-VF: " + str(epsilon_v))
            print("===================================================")
            print(v_k1[0:4])
            print(v_k1[4:8])
            print(v_k1[8:12])
            print("===================================================")
            break            
            
        
        
#     print(graph_list)

if __name__ == "__main__":
    main()

Wall time: 0 ns
=================== FINAL RESULT ==================
Iterations: 4
Gamma: 0.9999999
Epsilon for state-VF: 0.001
[0.81155786 0.86780798 0.91780809 1.        ]
[ 0.76155776  0.          0.66027378 -1.        ]
[0.70530765 0.65530757 0.61141485 0.38792427]


In [19]:
''' Results of Value Iteration Algorithm:
=================== FINAL RESULT ==================
Iterations: 41
Delta: 9.328160466282043e-11
Gamma: 0.9999999
Epsilon: 0.001
===================================================
[0.81155786 0.86780798 0.91780809 1.        ]
[ 0.76155776  0.          0.66027378 -1.        ]
[0.70530765 0.65530757 0.61141485 0.38792427]
===================================================
'''

' Results of Value Iteration Algorithm:\n=================== FINAL RESULT ==================\nIterations: 41\nDelta: 9.328160466282043e-11\nGamma: 0.9999999\nEpsilon: 0.001\n===================================================\n[0.81155786 0.86780798 0.91780809 1.        ]\n[ 0.76155776  0.          0.66027378 -1.        ]\n[0.70530765 0.65530757 0.61141485 0.38792427]\n===================================================\n'